### ISSUE TITLE
Themes issue on potential future public servers

### ISSUE THREAD

**Issue by Darth-Ness** [redstone-dev/Snazzle#29]
The user's preferred theme is stored sever side. So every time one of the users of a public server changes the theme it will change for all users.
One potential way of fixing this problem would be storing the value in local storage instead of the server.

**Comment by Sasytoremember** [comment]
cookies

**Comment by redstone-scratch** [comment]
We might use Supabase for hosting our DB, so that's how we could do it. I want to keep it server-side because that's easier to implement.

**Comment by redstone-scratch** [comment]
Although, we haven't actually decided on using Supabase yet. Hmmm.

**Comment by redstone-scratch** [comment]
I'm going to use replit's database feature in the repl to account for this.

**Comment by Darth-Ness** [comment]
What's wrong with local storage?

**Comment by redstone-scratch** [comment]
I want to use as little JavaScript as possible for some reason lol

**Comment by redstone-scratch** [comment]
Yeah true

**Comment by redstone-dev** [comment]
i think this was fixed and has been for a while
