### ISSUE TITLE
Not sure how this could occur

### ISSUE THREAD

**Issue by redstone-dev** [redstone-dev/Snazzle#31]
I'll commit this to main soon, but I made it so that when you click on an image in the forums, it gets enlarged. Flask doesn't seem to be rendering the page correctly.
![image](https://github.com/redstone-scratch/Snazzle/assets/31410740/650ffff6-3d90-4c41-9883-774f135d2858)

**Comment by Darth-Ness** [comment]
I fixed this in my latest commit. Basically, the problem was with with '_base.html' . So I just removed it since most of that wasn't needed anyways for the images.

**Comment by redstone-scratch** [comment]
> I fixed this in my latest commit. Basically, the problem was with with '_base.html' . So I just removed it since most of that wasn't needed anyways for the images.

Did you remove the entire file???

**Comment by Darth-Ness** [comment]
Oops, sorry lol. Should I close this issue, or is there still a problem?

**Comment by redstone-scratch** [comment]
Idk, haven't tested it

**Comment by Darth-Ness** [comment]
Its already in the code. I didn't bother with a PR this time because it's such a small change,

**Comment by redstone-scratch** [comment]
Okay
