### ISSUE TITLE
Snazzle not working on replit

### ISSUE THREAD

**Issue by redstone-dev** [redstone-dev/Snazzle#38]
I have [an official Snazzle repl](https://replit.com/@redstonescratch/Snazzle-Repl) and it's not working. You should be able to access it at `Snazzle-Repl.redstonescratch.repl.co` but when I try to access it in a web browser the request just times out. How do I fix this?

**Comment by redstone-scratch** [comment]
Actually I have an idea

**Comment by Steve0Greatness** [comment]
Replace line `356` with

```python
app.run("0.0.0.0", 9000)
```

**Comment by redstone-scratch** [comment]
> Replace line `356` with
> 
> ```python
> app.run("0.0.0.0", 9000)
> ```

Thanks :D

Will changing `HOST` and `PORT` at the top of `main.py` change anything, or no?

**Comment by redstone-scratch** [comment]
Keeping this open because it still doesn't work on replit

**Comment by EngineerRunner** [comment]
just want to add, scratchDB's project information is terrible so most of the time on replit it will just show "A scratch project..." by "A scratch user...", so its best to just self-host if you want to use it for something other than the forums.

**Comment by redstone-scratch** [comment]
> just want to add, scratchDB's project information is terrible so most of the time on replit it will just show "A scratch project..." by "A scratch user...", so its best to just self-host if you want to use it for something other than the forums.

Ah, okay. Should I add a piece of text mentioning that on the repl, then?

**Comment by redstone-scratch** [comment]
Snazzle fully works on Replit.

**Comment by Steve0Greatness** [comment]
Note: You can use `https://scratchproxy.abhiramtx.repl.co/scratch/api/?endpoint=<Scratch-API-path>` to get info from the Scratch API.

Example:

```python
def get_featured_projects():
    r = requests.get("https://scratchproxy.abhiramtx.repl.co/scratch/api/?endpoint=proxy/featured")
    return r.json()
```

I'm aware that using web proxy services is kinda hacky, but it works.

**Comment by redstone-scratch** [comment]
Alright, will add now (first commit of today lol)

**Comment by redstone-dev** [comment]
it works now 🎉
