### ISSUE TITLE
Future Rust port??

### ISSUE THREAD

**Issue by redstone-dev** [redstone-dev/Snazzle#41]
🚀🚀🚀

Literally, since we'd probably be using the Rocket crate lmao

This will be relatively far in the future though

Anyways what do u guys think of a rust port

This would probably be in a separate repo, and we'd "code freeze" the Python version and just focus on the Rust port until both are equal and then we'd start phasing out the Python version

**Comment by davidtheplatform** [comment]
Actix is pretty similar to flask but in rust

**Comment by redstone-scratch** [comment]
Okay

**Comment by redstone-dev** [comment]
Inactive
