### ISSUE TITLE
ScratchBlocks support in forums

### ISSUE THREAD

**Issue by NotFenixio** [redstone-dev/Snazzle#48]
So, I've ~coded~ added 2 lines to `_base.html` with which the ScratchBlocks text is rendered

I was wondering if it would be better to use the 2.0 blocks instead of the 3.0 ones. 3.0 ones are bigger and take up a lot of post space (the size is set to 1, the minimum, and still the 3.0 ones look very big).

https://snazzle-scratch3.notfenixio1.repl.co/forums/topic/669945?page=0 <-- ScratchBlocks 3
https://snazzle-scratch2.notfenixio1.repl.co/forums/topic/669945?page=0 <-- ScratchBlocks 2

Check what I've changed here: https://replit.com/@NotFenixio1/snazzle-scratch2#templates/_base.html

**Comment by redstone-dev** [comment]
Can't you just resize it without changing block padding? Or no?

**Comment by NotFenixio** [comment]
Oh, I forgot that English decimals are shown with . and not with ,

Anyways, I'm happy to help :)

**Comment by NotFenixio** [comment]
> After some tweaking, I think 0.6 is the best size.

Uh, that size seems to be a bit small, maybe it's my browser.
What about creating a setting for changing the size?

**Comment by redstone-dev** [comment]
> > After some tweaking, I think 0.6 is the best size.
> 
> Uh, that size seems to be a bit small, maybe it's my browser. What about creating a setting for changing the size?

Yeah, good idea.
