### ISSUE TITLE
I got the search function working!

### ISSUE THREAD

**Issue by NotFenixio** [redstone-dev/Snazzle#50]
Hey guys!
I got the search function working omg! (real!!1!!)

Check at: https://snazzle-scratch3.notfenixio1.repl.co/trending
The feature is not searching anything because the API blocked replit.
Check out the changes at https://replit.com/@NotFenixio1/snazzle-scratch3#main.py, line 352 (ctrl + g) and https://replit.com/@NotFenixio1/snazzle-scratch3#templates/search.html

I need to get the buttons working, but idk if you can submit multiple forms at the same time.

**Comment by NotFenixio** [comment]
I'll start making the pr

**Comment by NotFenixio** [comment]
#51

**Comment by redstone-dev** [comment]
pr was merged 🎉
