### ISSUE TITLE
crash when accessing project with scratchDB

### ISSUE THREAD

**Issue by EngineerRunner** [redstone-dev/Snazzle#55]
if scratchdb is down, it is set to use scratchdb and you attempt to access a project, it shows an error.
it just needs to be in a try-except statement.

**Comment by NotFenixio** [comment]
It is okay to use the Scratch API as a fallback even if use_ScratchDB is true?

**Comment by redstone-dev** [comment]
> It is okay to use the Scratch API as a fallback even if use_ScratchDB is true?

No, because when `USE_SCRATCHDB` is `True` it means that Snazzle is most likely being used in an environment where the Scratch API is not available.

**Comment by redstone-dev** [comment]
I think this was fixed a while ago.
