### ISSUE TITLE
Getting topics with ScratchDB doesn't always work

### ISSUE THREAD

**Issue by davidtheplatform** [redstone-dev/Snazzle#56]
Sometimes when you load a forum topic page scratchDB just doesn't respond. I don't think this is a problem with snazzle but there isn't any error checking (it's line 137 in dazzle.py).
Also sort of a seperate issue, but when a dazzle.py function returns an error the user just sees a back button and nothing else.

**Comment by redstone-dev** [comment]
I'm going to fix both of those.

<small>We definitely need to do more testing lol</small>

**Comment by redstone-dev** [comment]
We're working on #58 which will fix this
